work-base-dir = "./tmp"
listen-on = ":8080"
all-streams-playlist = true

[streams.pipe]
type = "pipe"
mime-type = "video/mp2t"
command = "ffmpeg -f lavfi -re -i sine=frequency=1000 -f lavfi -re -i testsrc=size=1920x1080:rate=25 -c:v libx264 -f mpegts -y output.pipe"
timeout = 15

[streams.file]
type = "file"
command = "ffmpeg -f lavfi -re -i sine=frequency=1000 -f lavfi -re -i testsrc=size=1920x1080:rate=25 -c:v libx264 -f hls -g 25 -hls_time 2 -hls_list_size 5 -hls_flags delete_segments+omit_endlist stream.m3u8"
timeout = 15
playlist = "stream.m3u8"

[[template]]
name = "test-screen:{res}@{fps}"
command = "ffmpeg -f lavfi -re -i sine=frequency=1000 -f lavfi -re -i testsrc2=size={res}:rate={fps} -c:v libx264 -f mpegts -y output.pipe"
timeout = 15
mime-type = "video/mp2t"
type = "pipe"
variants = [
	{ res = "1280x720", fps = "25" },
	{ res = "1280x720", fps = "60" },
	{ res = "1920x1080", fps = "25" },
	{ res = "1920x1080", fps = "60" }
]
