work-base-dir = "./tmp"
listen-on = ":8080"

[streams.pipe]
type = "pipe"
mime-type = "video/mp2t"
command = "ffmpeg -f lavfi -re -i sine=frequency=1000 -f lavfi -re -i testsrc=size=1920x1080:rate=25 -c:v libx264 -f mpegts -"
timeout = 15

[streams.file]
type = "file"
mime-type = "application/vnd.apple.mpegurl"
command = "ffmpeg -f lavfi -re -i sine=frequency=1000 -f lavfi -re -i testsrc=size=1920x1080:rate=25 -c:v libx264 -f hls -g 25 -hls_time 2 -hls_list_size 5 -hls_flags delete_segments+omit_endlist stream.m3u8"
timeout = 15
playlist = "stream.m3u8"
